# This is a config for E2B sandbox template.
# You can use template ID (wxtw93ue6h5z6colwt0i) or template name (vibe-nextjs-1753716200) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-1753716200") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-1753716200") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-1753716200')

team_id = "8fdb1945-7d80-4e65-bc8e-c14e87175d49"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-1753716200"
template_id = "wxtw93ue6h5z6colwt0i"
